### ISSUE TITLE
malware-analysis schema requires 'result', spec says 'av_result'.

### ISSUE THREAD

**Issue by cvoid-newcontext** [oasis-open/cti-stix-validator#184]
The spec for the malware analysis SDO defines the 'av_result' property but the validator expects the property to be named 'result'.

**Comment by rpiazza** [comment]
@cvoid-newcontext 

It was  'av_result' in one of the past working documents for 2.1 (see https://github.com/oasis-tcs/cti-stix2/issues/213), but if you look on page 94 of the oasis standard (see https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.pdf) you will see it has been changed to just 'result'.  If I remember correctly, this was because there might be "results" from different tools, not just anti-virus ones.
