### ISSUE TITLE
Relax jsonschema dependency

### ISSUE THREAD

**Issue by ostefano** [oasis-open/cti-stix-validator#224]
Any hard reason why the `jsonschema` dependency is so restrictive: `jsonschema[format-nongpl]>=4.6.0,<4.18.0`?

As things stand it is not possible to install `cti-stix-validator` together with `pymisp`, with `cti-stix-validator` having the most restrictive selection.

**Comment by ejratl** [comment]
As I recall, there was a breaking change in jsonschema that requires updates to the validator code to work with 4.18.0 and later. Since we don't yet have a pull request for the new way of doing things, upgrading to the latest version of jsonschema is not possible. 
The release notes for jsonschema 4.18.0 describe the change that is needed: https://github.com/python-jsonschema/jsonschema/releases/tag/v4.18.0
"jsonschema.RefResolver is now deprecated in favor of the new [referencing library](https://github.com/python-jsonschema/referencing/)."

**Comment by ejratl** [comment]
This issue is a duplicate of #216

**Comment by ostefano** [comment]
@ejratl what is the correct way to run the tests? Cloning and running pytest doesn't seem to work (more than two thirds of tests failing)

**Comment by ostefano** [comment]
Here the PR fixing this issue: https://github.com/oasis-open/cti-stix-validator/pull/228

**Comment by ostefano** [comment]
@clenk @rpiazza could you review the linked PR? Thanks!

**Comment by ostefano** [comment]
This has been fixed https://github.com/oasis-open/cti-stix-validator/pull/228
