### ISSUE TITLE
Duplicate UUIDs in bundle pass validation

### ISSUE THREAD

**Issue by jmgnc** [oasis-open/cti-stix-validator#27]
Attached is a file showing a bundle w/ duplicate UUID's, but the validator says that it passes validation fine.  It would be nice if the tool warned about such errors, where if the modified is the same, but properties differ, that it throws an error.

It is expected that a bundle could have multiple different versions of the same UUID, but in that case, the modified must be different.

Attached is a sample file.
[test.txt](https://github.com/oasis-open/cti-stix-validator/files/1126235/test.txt)

**Comment by gtback** [comment]
Thanks, @jmgnc . I have a feeling this will be somewhat difficult to solve in a generic way (if the IDs are the same, and if modified is the same, then no other properties can be different, etc.). 

Is there a requirement in the spec explicitly forbidding this (other than the generic requirements around versioning)? My first impression is that this should be a SHOULD check rather than a MUST, because it's not really the bundle itself that is invalid, but instead one of the two objects, but it's impossible in the general case to know which.

@clenk, @johnwunder, what do you think?

**Comment by clenk** [comment]
Is there a case where you would want to put two copies of the same object (id, modified, all properties identical) in the same bundle? If the validator sees two objects with the same UUID, could we just check that the modified property is different and throw an error if they're the same? In other words there is no need to check every single property.

I was thinking of this check as an extra check the validator just always runs, like our check that timestamps are sane (ie. there is no 13th month).

**Comment by gtback** [comment]
@clenk I like that approach. @jmgnc does that sound reasonable?

**Comment by jmgnc** [comment]
I think a warning/should for the duplicate UUID/modified date would be fine.  I don't think we can make this an explicit fail as there is nothing in the spec that specifically disallows entirely duplicated objects in a bundle.
