### ISSUE TITLE
The validator logger has introduced problems for the elevator logger

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-stix-validator#62]
Once the validator 1.0.1 was used with the elevator, each elevator message was output twice.

This temporary fix (https://github.com/oasis-open/cti-stix-elevator/commit/b7ce45baf17c0652afaf536415a3781021000f49) in the elevator solved the problem, but we should look into how loggers work together when stix utilities call each other.

**Comment by gtback** [comment]
Part of the issue is that the stix2-validator should perhaps not configure logging when it is [loaded as a library](https://github.com/oasis-open/cti-stix-validator/blob/master/stix2validator/__init__.py#L14), only when it is [running as a script](https://github.com/oasis-open/cti-stix-validator/blob/master/stix2validator/scripts/stix2_validator.py#L15).
