### ISSUE TITLE
cpe:2.3:o:microsoft:windows_xp:-:sp2:*:*:*:*:*:* Fails

### ISSUE THREAD

**Issue by timngo1** [oasis-open/cti-stix-validator#90]
I got the official CPE name for this version of windows from https://nvd.nist.gov/products/cpe/detail/70394 but it is failing the validator script.

It looks like it has a problem with the "-" between windows_xp and sp2 which is supposed to be the version number. It makes sense that "-" is a bad version number but if that is what is listed as the official cpe name it should pass right?

**Comment by clenk** [comment]
Thank you, @timngo1; we'll have to fix this in the JSON schemas.

**Comment by clenk** [comment]
This was fixed in the schemas in this commit: https://github.com/oasis-open/cti-stix2-json-schemas/commit/768be302cdad4b0fb7f68c6c8ffa54a81537829f

It has now been included in the validator, too, with https://github.com/oasis-open/cti-stix-validator/commit/78a28d8d72d6ad50dac0c82a103741abbd33aada.

Let us know if you run into any other issues.
